---
- hosts: all
  tasks:
  - name: register phantomjs install
    stat:
        path: /usr/local/bin/phantomjs
    register: phantomjs_stat

  - name: install phantomjs and diffengine dependency
    apt:
        name: '{{ item }}'
        state: present
    with_items:
        - python3-pip
        - libfontconfig

  - name: check version and register
    shell: phantomjs -v
    register: phantomjs_version
    when: phantomjs_stat.stat.exists == True

  - name: install phantomjs
    unarchive:
        src: 'https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2'
        dest: '/usr/local/share'
        remote_src: True
    when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'

  - name: create symbolic links
    file:
        src: '/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs'
        dest: '/usr/local/bin/phantomjs'
        state: link
    when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'

  - name: install diffengine
    pip:
        name: diffengine
        extra_args: '--process-dependency-links'
        executable: pip3
